gamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.games_index, name='index'),
    path('games/<int:game_id>/', views.games_detail, name='detail'),
    path('games/<int:game_id>/add_note/', views.add_note, name='add_note'),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='games_delete'),
    
    path('consoles/', views.ConsoleList.as_view(), name='consoles_index'),
    path('consoles/<int:pk>/', views.ConsoleDetail.as_view(), name='consoles_detail'),
    path('consoles/create/', views.ConsoleCreate.as_view(), name='consoles_create'),
    path('consoles/<int:pk>/update/', views.ConsoleUpdate.as_view(), name='consoles_update'),
    path('consoles/<int:pk>/delete/', views.ConsoleDelete.as_view(), name='consoles_delete'),

    path('games/<int:game_id>/assoc_console/<int:console_id>/', views.assoc_console, name='assoc_console'),
    path('games/<int:game_id>/unassoc_console/<int:console_id>/', views.unassoc_console, name='unassoc_console'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.

TYPE = (
    ('T', 'Thoughts'),
    ('R', 'Review'),
    ('P', 'Progress')
)


class Console(models.Model):
    name = models.CharField(max_length=50)
    released = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('consoles_detail', kwargs={'pk': self.id})

class Game(models.Model):
    name = models.CharField(max_length=100)
    finished = models.BooleanField(default=False)
    details = models.TextField(max_length=500)
    consoles = models.ManyToManyField(Console)
    genre = models.CharField(max_length=50)
    released = models.IntegerField()

    def __str__(self):
        return f'{self.name}({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})
    
    def posted_today(self):
        return self.note_set.filter(date=date.today())
    


class Note(models.Model):
    date = models.DateField('posted on', auto_now_add=True)
    content = models.CharField('add a note', max_length=500)
    type = models.CharField(
        'type of note',
        max_length=1,
        choices = TYPE,
        default=TYPE[0][0],
    )
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']
    
    def __str__(self):
        return f"{self.get_type_display()} on {self.date}"
    

main_app/forms.py
from django.forms import ModelForm
from .models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['content', 'type']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Game, Console
from .forms import NoteForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def games_index(request):
    games = Game.objects.all()
    return render(request, 'games/index.html', {'games': games})

def games_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    id_list = game.consoles.all().values_list('id')
    unassociated_consoles = Console.objects.exclude(id__in=id_list)

    note_form = NoteForm()
    return render(request, 'games/detail.html', {'game': game, 'note_form': note_form, 'consoles': unassociated_consoles})

class GameCreate(CreateView):
    model = Game
    fields =  ['name', 'finished', 'details', 'genre', 'released' ]

class GameUpdate(UpdateView):
    model = Game
    fields = '__all__'
    # ['finished', 'detail', 'console', 'genre', 'released' ]

class GameDelete(DeleteView):
    model = Game
    success_url = '/games'

def add_note(request, game_id):
    form = NoteForm(request.POST)
    if form.is_valid():
        new_note = form.save(commit=False)
        new_note.game_id = game_id
        new_note.save()
    return redirect('detail', game_id=game_id)


class ConsoleList(ListView):
  model = Console

class ConsoleDetail(DetailView):
  model = Console

class ConsoleCreate(CreateView):
  model = Console
  fields = '__all__'

class ConsoleUpdate(UpdateView):
  model = Console
  fields = ['name', 'released']

class ConsoleDelete(DeleteView):
  model = Console
  success_url = '/consoles'

def assoc_console(request, game_id, console_id):
   Game.objects.get(id=game_id).consoles.add(console_id)
   return redirect('detail', game_id=game_id)

def unassoc_console(request, game_id, console_id):
   Game.objects.get(id=game_id).consoles.remove(console_id)
   return redirect('detail', game_id=game_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Retro Game Collector</h1>

{% endblock content %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Retro Game Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li>
            <a href="/" class="left brand-logo">&nbsp;&nbsp;Retro Game Collector</a>
          </li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'consoles_create' %}">Add a Console</a></li>
          <li><a href="{% url 'consoles_index' %}">View All Consoles</a></li>
          <li><a href="{% url 'index' %}">View All Video Games</a></li>
          <li><a href="{% url 'games_create' %}">Add a Game</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">{% block content %} {% endblock %}</main>
  <footer class="page-footer">
    <div class="right">
      All Rights Reserved, &copy; 2023 Retro Game Collector &nbsp;
    </div>
  </footer>
</body>

</html>

main_app/templates/games/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ game.name }}</span>
        <div>
          <b>
            <p>Status:
          </b>
          {% if game.finished %}Finished</p>
          {% else %}
          Not finished</p>
          {% endif %}
          <p><b>Details:</b> {{ game.details|linebreaks }}</p>
          <p><b>Console:</b> {{ game.console }}</p>
          <p><b>Genre:</b> {{ game.genre }}</p>
          <p>
            {% if game.released > 2000 %}
            <b>MODERN</b>
            ({{ game.released }})
          </p>
          {% else %}
          <b>RETRO</b>
          ({{ game.released }})</p>
          {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'games_update' game.id %}">Edit</a>
          <a href="{% url 'games_delete' game.id %}">Delete</a>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">

      <h6 id="darktext">{{ game.name }} was released on:</h6>
      {% if game.consoles.count %}
      {% for console in game.consoles.all %}
      <div class="card">
        <div class="card-content">
          <div class="col">
          {{ console.name }}</div>
          <p id="align-right">
            <a href="{% url 'unassoc_console' game.id console.id %}">x</a>
          </p>
        </div>
      </div>
      {% endfor %}
      {% else %}
      (No console listed yet)
      {% endif %}
    </div>

    <div class="col s12">
      <h6 id="darktext">Add a console?</h6>

      {% for console in consoles.all %}
      <div class="card">
        <div class="card-content">
          {{ console.name }}
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_console' game.id console.id  %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
      {% endfor %}

    </div>


  </div>

  <div class="row">
    <div class="col s6">
      <form action="{% url 'add_note' game.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ note_form.as_p }}
        <input type="submit" class="btn" value="Add Note">
      </form>

      <br>
      {% if game.posted_today %}
      <div class="card">{{game.name}} has a new post today!</div>
      {% else %}
      <div class="card">{{game.name}} has no recent posts.</div>
      {% endif %}

      {% for note in game.note_set.all %}
      <div class="card">
        <table class="striped">
          <tbody></tbody>
          <tr>
            <th>{{note.date}}</th>
            <th>Category: {{note.get_type_display}}</th>
          </tr>
          <tr>
            <td colspan="2">{{note.content}}</td>
          </tr>
          </tbody>
        </table>
      </div>
      {% endfor %}
    </div>

  </div>
</div>




<script>
  const selectEl = document.getElementById('id_type');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/games/index.html
{% extends 'base.html' %}
{% block content %}

<h1 id="darktext">Game List</h1>
{% for game in games %}
<div class="card">
  <!-- Add this <a> tag -->
  <a href="/games/{{ game.id }}">
    <div class="card-content">
      <span class="card-title">{{ game.name }}</span>  </a>
      <b><p>Status:</b> 
        {% if game.finished %}Finished</p>
      {% else %}
      Not finished</p>
      {% endif %}
      <p><b>Console:</b> {{ game.console }}</p>
      <p><b>Genre:</b> {{ game.genre }}</p>
      <p>
      {% if game.released > 2000 %}
        <b>MODERN</b>
        ({{ game.released }})</p>
      {% else %}
        <b>RETRO</b>
        ({{ game.released }})</p>
      {% endif %}

     
    </div>

</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

{% endblock content %}

main_app/templates/main_app/console_confirm_delete.html
test

main_app/templates/main_app/console_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Console Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ console.name }}</span>
        <p>Year: {{ console.released }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'consoles_update' console.id %}">Edit</a>
        <a href="{% url 'consoles_delete' console.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Games collected:</span>
        {% if console.game_set.count %}
      {% for game in console.game_set.all %}
      <a href="/games/{{ game.id }}">
      <p>{{game.name}}</p></a>
      {% endfor %}
      {% else %}
        <p>No games for this console 🎮 </p>
      {% endif %}
      </div>
    </div>
  </div>
</div>





{% endblock %}

main_app/templates/main_app/console_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Game</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/console_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Console List</h1>

{% for console in console_list %}
  <a href="{% url 'consoles_detail' console.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ console.name }}</span>
            <p>Color: {{ console.released }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete {{object.name}}</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' game.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h3>Edit <span class="teal-text">{{object.name}}</span></h3>
{% else %}
<h3>Add Game</h3>
{% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}